version: '2'
services:
  front:
    # Use NGINX stable container
    image: nginx:stable
    volumes:
      - "/usr/local/nginx.conf:/etc/nginx/conf.d/default.conf"
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app
    links:
      - app
  app:
    image: ghost:0.9.0
    restart: always
